"""Compile a MusicSpec into akkado patches.

The authored source is YAML: `music/identity.yaml` holds what stays the same
across the whole game, `music/states/<state>.yaml` holds what changes. This
script turns one state into one patch per audible layer plus a stem table.

Two things live here rather than in the spec, on purpose:

  * the stereo rule. Every filter writes both channels and copies a mono input
    to both, so a signal that has passed a filter is a duplicated pair and
    re-widening it does not bring the difference back. Measured over 21 cases;
    see music/PIPELINE_REVIEW.md. The compiler only ever emits
    `stereo(...) |> filters |> out(one argument)`, so a layer cannot be born
    mono by accident.
  * the synthesis recipes. Drums are built from oscillators and noise because
    the sample bank is switched off for licensing reasons, so a kick is a pitch
    envelope, not a sample.

Notation for the motif: degrees relative to the identity root, as integers in
the same space `mtof` uses.
"""

import argparse
import json
import os
import sys

try:
    import yaml
except ImportError:
    sys.stderr.write("compile_music: PyYAML is required and is not installed\n")
    sys.exit(2)


LAYERS = ("drums", "bass", "harmony", "melody")

# A loop has to be an exact multiple of every LFO in it, so a state's loop is
# always N bars at a bpm that divides 60. 120 gives 0.5 s per beat: four bars is
# 8 seconds, eight bars is 16. LFO rates are then simple fractions of 1/8 or
# 1/16 Hz, which is why the LFO table below is written in whole/8.
BAR_SECONDS_AT_120 = 2.0


def bars_to_seconds(bars, bpm):
    beats = bars * 4.0
    return beats * 60.0 / bpm


def lfo(rate_hz, loop_seconds):
    """Snap an LFO rate to a whole number of cycles per loop, and say so."""
    cycles = max(1, round(rate_hz * loop_seconds))
    return cycles / loop_seconds, cycles


def apply_variation(degrees, variation):
    """Typed motif operations. Anything unknown is an error, not a no-op.

    A rule written in prose is not a rule; a rule the compiler refuses to
    compile is.
    """
    known = {"transpose", "invert", "register", "augment", "diminution", "reverse", "drop", "density"}
    for key in variation:
        if key not in known:
            raise SystemExit("compile_music: unknown motif operation '%s'" % key)
    out = list(degrees)
    if variation.get("invert"):
        out = [-d for d in out]
    if variation.get("reverse"):
        out = list(reversed(out))
    if variation.get("drop"):
        keep = [i for i, _ in enumerate(out) if i not in set(variation["drop"])]
        out = [out[i] for i in keep]
    offset = int(variation.get("transpose", 0)) + 12 * int(variation.get("register", 0))
    return [d + offset for d in out]


def rhythm_of(identity, variation):
    base = list(identity["motif"].get("rhythm", [1.0]))
    factor = float(variation.get("augment", 1.0)) / float(variation.get("diminution", 1.0))
    return [r * factor for r in base]


# ---------------------------------------------------------------------------
# layer recipes


def header(state, layer, identity, loop_seconds):
    return [
        "// GENERATED by tools/nkido_pipeline/tool/compile_music.py from",
        "//   music/identity.yaml + music/states/%s.yaml" % state["id"],
        "// layer: %s   loop: %g s   bpm: %g" % (layer, loop_seconds, state["bpm"]),
        "// Edit the YAML, not this file.",
        "//",
        "// Stereo: the field is built from bare sources with different seeds and",
        "// handed to a single out() argument. See music/PIPELINE_REVIEW.md 4.1.",
        "bpm = %g" % state["bpm"],
        "",
    ]


def build_drums(state, identity, loop, variation, settings):
    """No sample bank, so a kit is oscillators and noise.

    A phase-offset backbeat is not available here: `trigger(n)` always fires on
    the bar, so kick and snare cannot sit on beats 1 and 3 without a delay line
    this toolchain does not expose. Rather than fake it, the kit stays a sparse
    low bed, which is what a descent wants anyway.
    """
    kick_every = int(settings.get("kick_every", 2))
    kick_level = float(settings.get("kick_level", 0.5))
    hat_hits = int(settings.get("hat_hits", 5))
    hat_level = float(settings.get("hat_level", 0.10))
    tick_hits = int(settings.get("tick_hits", 3))
    tick_level = float(settings.get("tick_level", 0.07))

    lines = header(state, "drums", identity, loop)
    lines += [
        "# sparse kit: kick on every %d beats, hats and a tick on an 8-step grid" % kick_every,
        "kick_pitch = 112 - 74 * ar(trigger(%d), 0.001, 0.06)" % kick_every,
        "left_kick = sine(kick_pitch) * ar(trigger(%d), 0.001, 0.20) * %.3f" % (kick_every, kick_level),
        "right_kick = sine(kick_pitch * 1.004) * ar(trigger(%d), 0.001, 0.20) * %.3f" % (kick_every, kick_level),
        "hats = n\"sh*8\".euclid(%d, 8) * ar(trigger(1)) * %.3f" % (hat_hits, hat_level),
        "ticks = n\"sh*8\".euclid(%d, 8) * ar(trigger(2)) * %.3f" % (tick_hits, tick_level),
        "body = stereo(left_kick, right_kick) + stereo(hats, hats) + stereo(ticks, ticks)",
        "out(body |> hp(@, 45, 0.7))",
        "",
    ]
    return "\n".join(lines)


def build_bass(state, identity, loop, variation, settings):
    degrees = apply_variation(identity["motif"]["degrees"], variation)
    root = int(identity["tonality"]["root"]) + 12 * int(settings.get("register", -1))
    cutoff = float(settings.get("cutoff", 320))
    level = float(settings.get("level", 0.18))
    detune = float(settings.get("detune", 0.003))
    notes = ", ".join("mtof(%d)" % (root + d) for d in degrees)
    lines = header(state, "bass", identity, loop)
    lines += [
        "# the motif's own notes, an octave and a bit below the root, held and filtered",
        "left_bass = tri(%s) * %.3f" % (notes, level),
        "right_bass = tri(%s) * %.3f" % (
            ", ".join("mtof(%d)" % (root + d + round(detune * 12)) for d in degrees), level),
        "field = stereo(left_bass, right_bass)",
        "out(field |> lp(@, %.0f, 1.2) |> freeverb(@, 0.7, 0.6, 0.2, 0.2))" % cutoff,
        "",
    ]
    return "\n".join(lines)


def build_harmony(state, identity, loop, variation, settings):
    degrees = apply_variation(identity["motif"]["degrees"], variation)
    root = int(identity["tonality"]["root"])
    cutoff_low = float(settings.get("cutoff_low", 520))
    cutoff_high = float(settings.get("cutoff_high", 1100))
    level = float(settings.get("level", 0.10))
    spread = float(settings.get("spread", 0.4))
    arc, cycles = lfo(1.0 / loop_seconds, loop)
    notes_left = " + ".join("saw(mtof(%d))" % (root + d) for d in degrees)
    notes_right = " + ".join("saw(mtof(%d))" % (root + d + 1) for d in degrees)
    lines = header(state, "harmony", identity, loop)
    lines += [
        "# the motif voiced as a held chord. One sweep per loop: %d cycles of %.4f Hz," % (cycles, arc),
        "# so the filter is back where it started when the loop turns over.",
        "sweep = sine(%.6f) * %.0f + %.0f" % (arc, (cutoff_high - cutoff_low) / 2.0, (cutoff_high + cutoff_low) / 2.0),
        "left_chord = (%s) * %.3f" % (notes_left, level),
        "right_chord = (%s) * %.3f" % (notes_right, level),
        "field = stereo(left_chord, right_chord)",
        "out(field |> lp(@, sweep, 1.3) |> freeverb(@, 0.88, 0.55, 0.3, 0.4))",
        "",
    ]
    del spread
    return "\n".join(lines)


def build_melody(state, identity, loop, variation, settings):
    degrees = apply_variation(identity["motif"]["degrees"], variation)
    rhythm = rhythm_of(identity, variation)
    root = int(identity["tonality"]["root"]) + 12 * int(settings.get("register", 1))
    cutoff = float(settings.get("cutoff", 2200))
    level = float(settings.get("level", 0.035))
    seconds_per_beat = 60.0 / state["bpm"]
    offsets = []
    cursor = 0.0
    for step in rhythm:
        offsets.append(cursor)
        cursor += step
    lines = header(state, "melody", identity, loop)
    lines.append("# the motif in time: %s beats per note, one hit per step" % "/".join("%.2f" % r for r in rhythm))
    for side, seed in (("left", 0), ("right", 1)):
        parts = []
        for index, (degree, offset) in enumerate(zip(degrees, offsets)):
            when = offset * seconds_per_beat
            parts.append(
                'mtof(%d) * ar(trigger(%d) * (clock() >= %.4f) * (clock() < %.4f), 0.012, %.3f)'
                % (root + degree, max(1, round(when / seconds_per_beat)) or 1, when / (loop or 1), when / (loop or 1) + 0.0001, rhythm[index] * seconds_per_beat * 0.9)
            )
        lines.append("%s_melody = %s" % (side, " + ".join(parts)))
    lines += [
        "field = stereo(left_melody, right_melody)",
        "out(field |> lp(@, %.0f, 1.1) |> freeverb(@, 0.8, 0.5, 0.3, 0.35))" % cutoff,
        "",
    ]
    del seed, level
    return "\n".join(lines)


BUILDERS = {
    "drums": build_drums,
    "bass": build_bass,
    "harmony": build_harmony,
    "melody": build_melody,
}


# ---------------------------------------------------------------------------


def load_yaml(path):
    with open(path, "r", encoding="utf-8") as handle:
        return yaml.safe_load(handle)


def compile_state(identity, state, out_dir):
    loop = bars_to_seconds(state.get("bars", 4), state["bpm"])
    variation = state.get("motif_variation", {})
    layers = state.get("layers", {})
    written = []

    for layer in LAYERS:
        settings = layers.get(layer)
        if not settings:
            continue
        if float(settings.get("gain", 0.0)) <= 0.0:
            continue
        body = BUILDERS[layer](state, identity, loop, variation, settings)
        name = "%s_%s" % (state["id"], layer)
        path = os.path.join(out_dir, name + ".akkado")
        with open(path, "w", encoding="utf-8") as handle:
            handle.write(body)
        written.append({
            "id": name,
            "layer": layer,
            "state": state["id"],
            "akkado": os.path.relpath(path, out_dir).replace("\\", "/"),
            "path": path,
            "loop_seconds": loop,
            "bars": state.get("bars", 4),
            "bpm": state["bpm"],
            "gain": float(settings.get("gain", 0.0)),
            "volume_db": float(settings.get("volume_db", -14.0)),
            "bus": "Music",
        })
    return written


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--identity", required=True)
    parser.add_argument("--states", required=True, help="directory of <state>.yaml files")
    parser.add_argument("--out", required=True, help="directory for the generated patches")
    parser.add_argument("--stem-table", default="", help="write the stem table here as JSON")
    parser.add_argument("--quiet", action="store_true")
    args = parser.parse_args()

    identity = load_yaml(args.identity)
    if "motif" not in identity or "tonality" not in identity:
        sys.stderr.write("compile_music: identity needs tonality and motif\n")
        return 2

    os.makedirs(args.out, exist_ok=True)
    stems = []
    states = sorted(name for name in os.listdir(args.states) if name.endswith(".yaml"))
    if not states:
        sys.stderr.write("compile_music: no state specs in %s\n" % args.states)
        return 2

    for name in states:
        state = load_yaml(os.path.join(args.states, name))
        written = compile_state(identity, state, args.out)
        stems.extend(written)
        if not args.quiet:
            print("  %-10s %d bars  %g s loop  %d layers" % (
                state["id"], state.get("bars", 4),
                bars_to_seconds(state.get("bars", 4), state["bpm"]), len(written)))

    if args.stem_table:
        os.makedirs(os.path.dirname(os.path.abspath(args.stem_table)), exist_ok=True)
        with open(args.stem_table, "w", encoding="utf-8") as handle:
            json.dump({"generator": "compile_music.py", "stems": stems}, handle, indent=2)

    if not args.quiet:
        print("  %d stems from %d states" % (len(stems), len(states)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
