class_name DescentAmbience
extends Node

## Dynamic ambience for the descent: every stem loops forever, and a profile is
## nothing but a row of per-stem gains. The Kit picks a profile and the mixer
## crossfades. Nothing is stopped and started, so stem phase never jumps and
## the room keeps sounding like one room while the mix changes underneath it.
##
## The data is generated by tools/nkido_pipeline/ from ambient.json. That file
## is the only place a stem or a profile is authored.

const DEFAULT_STEMS_PATH: String = "res://modules/descent_exploration/ambient_stems.json"
const SILENCE_DB: float = -80.0

## Fraction of a percent of pitch drift per cycle. Two 16 s loops started at the
## same moment would otherwise stay phase-locked forever and read as one much
## longer loop. Godot wraps loops on frame boundaries, so this cannot click.
const PITCH_DRIFT: float = 0.003
const PITCH_DRIFT_RATE: float = 0.07
const PITCH_DRIFT_STEMS: float = 0.83

var _players: Dictionary = {}
var _base_db: Dictionary = {}
var _phase: Dictionary = {}
var _target_db: Dictionary = {}
var _from_db: Dictionary = {}
var _fade_time: float = 0.0
var _fade_elapsed: float = 0.0
var _clock: float = 0.0
var _bus: StringName = &"Music"
var _profiles: Dictionary = {}
var _order: Array[String] = []
var _current: StringName = &""


func _ready() -> void:
	set_process(false)


## Returns the problems it found. Empty array means the mix is live.
func setup(stems_path: String = DEFAULT_STEMS_PATH, bus: StringName = &"Music") -> PackedStringArray:
	var problems := PackedStringArray()
	var raw: Variant = _load_json(stems_path)
	if raw == null:
		problems.append("ambient: cannot read %s" % stems_path)
		return problems
	if not (raw is Dictionary):
		problems.append("ambient: %s is not a JSON object" % stems_path)
		return problems
	var data: Dictionary = raw

	_bus = bus
	_profiles = {}
	var profile_names: Dictionary = data.get("profiles", {})
	for name: Variant in profile_names:
		if not (profile_names[name] is Dictionary):
			problems.append("ambient: profile '%s' is not an object" % name)
			continue
		var gains: Dictionary = {}
		for stem_id: Variant in (profile_names[name] as Dictionary).get("gains", {}):
			gains[String(stem_id)] = clampf(float((profile_names[name] as Dictionary)["gains"][stem_id]), 0.0, 1.0)
		_profiles[String(name)] = gains

	var entries: Array = data.get("stems", [])
	if entries.is_empty():
		problems.append("ambient: no stems in %s" % stems_path)
		return problems

	var index := 0
	for entry: Variant in entries:
		var stem_id := String((entry as Dictionary).get("id", ""))
		var file := String((entry as Dictionary).get("file", ""))
		if stem_id == "":
			problems.append("ambient: stem with no id")
			continue
		if _players.has(stem_id):
			problems.append("ambient: duplicate stem '%s'" % stem_id)
			continue
		if not file.begins_with("res://"):
			problems.append("ambient: stem '%s' file must be res://, got '%s'" % [stem_id, file])
			continue
		if not ResourceLoader.exists(file):
			problems.append("ambient: stem '%s' file not found '%s'" % [stem_id, file])
			continue
		if not _profiles.is_empty() and not _any_profile_uses(stem_id):
			problems.append("ambient: stem '%s' is in no profile" % stem_id)
			continue

		var stream := _looping_copy(file)
		if stream == null:
			problems.append("ambient: stem '%s' did not import as AudioStreamWAV" % stem_id)
			continue

		var player := AudioStreamPlayer.new()
		player.name = "Stem_" + stem_id
		player.stream = stream
		player.bus = _bus
		player.volume_db = SILENCE_DB
		add_child(player)
		player.play()

		var base := float((entry as Dictionary).get("volume_db", -18.0))
		_players[stem_id] = player
		_base_db[stem_id] = base
		_target_db[stem_id] = SILENCE_DB
		_from_db[stem_id] = SILENCE_DB
		_phase[stem_id] = float(index) * PITCH_DRIFT_STEMS
		index += 1

	for profile_name: String in _profiles:
		for stem_id: String in _profiles[profile_name]:
			if not _players.has(stem_id):
				problems.append("ambient: profile '%s' names stem '%s' which is not loaded" % [profile_name, stem_id])
	_order = _profile_order()
	return problems


func profile_names() -> PackedStringArray:
	return PackedStringArray(_order)


func current_profile() -> StringName:
	return _current


func stem_ids() -> PackedStringArray:
	return PackedStringArray(_players.keys())


## Crossfades to a profile. fade_seconds 0 snaps. Returns false for an unknown
## name and changes nothing.
func apply_profile(profile_name: String, fade_seconds: float = 4.0) -> bool:
	if not _profiles.has(profile_name):
		return false
	_from_db = _target_db.duplicate()
	for stem_id: String in _players:
		var gain := float((_profiles[profile_name] as Dictionary).get(stem_id, 0.0))
		_target_db[stem_id] = SILENCE_DB if gain <= 0.0 else _base_db[stem_id] + linear_to_db(gain)
	_fade_time = maxf(fade_seconds, 0.0)
	_fade_elapsed = 0.0
	_current = StringName(profile_name)
	if _fade_time <= 0.0:
		_write(_target_db)
		set_process(false)
	else:
		set_process(true)
	return true


## Immediate silence without stopping the players, so the next profile starts
## from the same phase the room was holding.
func fade_out(fade_seconds: float = 2.0) -> void:
	_from_db = _target_db.duplicate()
	for stem_id: String in _players:
		_target_db[stem_id] = SILENCE_DB
	_fade_time = maxf(fade_seconds, 0.0)
	_fade_elapsed = 0.0
	_current = &""
	if _fade_time <= 0.0:
		_write(_target_db)
		set_process(false)
	else:
		set_process(true)


func _process(delta: float) -> void:
	_clock += delta
	for stem_id: String in _players:
		var player: AudioStreamPlayer = _players[stem_id]
		player.pitch_scale = 1.0 + PITCH_DRIFT * sin(_clock * PITCH_DRIFT_RATE * 6.2831853 + float(_phase[stem_id]))

	if _fade_time <= 0.0:
		set_process(false)
		return
	_fade_elapsed = minf(_fade_elapsed + delta, _fade_time)
	var t := _fade_elapsed / _fade_time
	var frame := _target_db.duplicate()
	for stem_id: String in frame:
		frame[stem_id] = lerpf(float(_from_db[stem_id]), float(_target_db[stem_id]), t)
	_write(frame)
	if _fade_elapsed >= _fade_time:
		_write(_target_db)
		set_process(false)


func _write(levels: Dictionary) -> void:
	for stem_id: String in levels:
		if _players.has(stem_id):
			(_players[stem_id] as AudioStreamPlayer).volume_db = float(levels[stem_id])


func _any_profile_uses(stem_id: String) -> bool:
	for profile_name: String in _profiles:
		if (_profiles[profile_name] as Dictionary).has(stem_id):
			return true
	return false


func _profile_order() -> Array[String]:
	var names: Array[String] = []
	for profile_name: String in _profiles:
		names.append(profile_name)
	names.sort()
	return names


func _looping_copy(path: String) -> AudioStreamWAV:
	var source := load(path) as AudioStreamWAV
	if source == null:
		return null
	var stream := source.duplicate() as AudioStreamWAV
	stream.loop_mode = AudioStreamWAV.LOOP_FORWARD
	stream.loop_begin = 0
	stream.loop_end = int(round(stream.get_length() * float(stream.mix_rate)))
	return stream


func _load_json(path: String) -> Variant:
	if not FileAccess.file_exists(path):
		return null
	var text := FileAccess.get_file_as_string(path)
	if text.is_empty():
		return null
	return JSON.parse_string(text)
